# Problem 2 - Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fibonacci_array = [1, 2]

while fibonacci_array.last < 4000000 do
  fibonacci_array << fibonacci_array[-1] + fibonacci_array[-2]
end

puts fibonacci_array.select { |n| n % 2 == 0 }.reduce(:+)